### ISSUE TITLE
code-generator does not work for PageYaml with "android" platform

### ISSUE THREAD

**Issue by mach6** [paypal/SeLion#184]
From http://paypal.github.io/SeLion/html/documentation.html#android-native-page-yaml

This (corrected with ending `"` on locators) example PageYaml does not work

``` yaml
baseClass: "com.paypal.selion.testcomponents.BasicPageImpl"
platform: "android"
defaultLocale: "US"
elements:
  shortPressButtonUiObject:
    locators:
      FR: "//TintButton[@value='Short Press']"
      US: "//TintButton[@value='Short Press']"
  shortPressLabelUiObject:
    locators:
      FR: "//TextView[contains(@value, ', short press')]"
      US: "//TextView[contains(@value, ', short press')]"
```

the resulting error is 

``` shell
[ERROR] SeLion code generator failed when generating code for {file}
[ERROR] Root Cause :
[ERROR] java.lang.IllegalArgumentException: Detected an invalid key [shortPressLabelUiObject] in data file {file} for Platform Android
```
