### ISSUE TITLE
Unclear documentation w.r.t defaultLocale / PageYaml

### ISSUE THREAD

**Issue by mach6** [paypal/SeLion#73]
Consider rephrasing this text and/or adding an example which walk through the design details;

```
defaultLocale: - The default locale to use if the PageYAML does not explicitly define a locale specific 
value. For example; A value of US will require US definitions in the PageYAML but if a test is currently 
running against the German version of a site and the DE definition does not exist for the queried 
attribute, then the US version will be used.
```

This documentation issue is rooted in this feedback;

```
I interpreted the phrase from documentation "if the PageYAML does not explicitly define a locale 
specific value" as a possibility to drop "US:" key *in locator* and use just a value without prefix. I 
thought that locators without a key will get the key from defaultLocale. Perhaps the doc should be 
rephrased as "if locator does not define a locale", or maybe just replace it with example. English is not 
good enough in situation like this one. 
```

An example walk-through could look like this;

You only need to specify the locator for any given element in a different locale when it is different from the defaultLocale's value. When the test is run, if there is no locator specified for your target locale, the locator for the `defaultLocale` is used. For example;

``` yaml
baseClass: "com.paypal.selion.testcomponents.BasicPageImpl"
pageTitle:
  US: "API Page"
elements:
  loginTextField:
    locators:
      US: "@id='txtUsername'"
  helpPageButton:
    locators:
      US: "@id='helpPageBtn'"
      UK: "@id='uk-helpPageBtn'"
defaultLocale: "US"
pageValidators: []
```

In this example, if you run a test with the locale = UK, the locators `@id='uk-helpPageBtn'` and `"@id='txtUsername'"` will be used for `helpPageButton` and `loginTextField`
